# Generated by Django 5.1.4 on 2024-12-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tax",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
