# Generated by Django 5.1.4 on 2024-12-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="address_1",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="address_2",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
